### ISSUE TITLE
issue with two or more images

### ISSUE THREAD

**Issue by doorbash** [AGulev/drawpixels#9]
Hi
I'm not sure if it is a bug of Defold Editor or `drawpixels`
With one image everything is fine and `drawpixels` works very well
but when I try to draw on two image for example when they are next to each other
only one of them shows its content at a time, and sometimes they show duplicate content. It's very weird and annoying. 
When I test it on Browser or Android its working fine.
I've made a very simple project to show you what I mean. You can play it in editor and move the player to right direction to see the issue.
Thanks
[trail-test.zip](https://github.com/AGulev/drawpixels/files/3230232/trail-test.zip)

**Comment by AGulev** [comment]
Thanks for the report I'll check it.

**Comment by AGulev** [comment]
It's the Editor issue, I created a bug: `Issue-4218` (#4218)

For now, as a workaround you can make a fast fix: just make some changes in one of the `png` files, they shouldn't be duplicates.

**Comment by doorbash** [comment]
Thank you so much for looking into this

**Comment by AGulev** [comment]
@doorbash fixed in the  editor

**Comment by doorbash** [comment]
@AGulev Yes it's fixed now. Thanks a lot ❤️
